### ISSUE TITLE
Enable test's code coverage monitoring

### ISSUE THREAD

**Issue by konard** [linksplatform/Ranges#36]
700 RUB reward can be claimed by anyone who completes this task.

## Codacy

https://app.codacy.com/manual/drakonard/Ranges/settings/coverage
https://github.com/marketplace/actions/codacy-coverage-reporter
https://github.com/codacy/codacy-coverage-reporter/blob/master/docs/index.md

## Coveralls

https://coveralls.io/github/linksplatform/Ranges
https://github.com/marketplace/actions/coveralls-github-action

## Tools

https://github.com/OpenCover/opencover
https://www.jetbrains.com/dotcover/

**Comment by Konard** [comment]
We will be using `OpenCover` instead of `dotcover`, because we currently don`t own the `dotcover`'s licence.

**Comment by Krol-X** [comment]
> GitHub Actions -> OpenCover -> Codacy

TODO:

1. Clone this repository
2. Install OpenCover
3. Learn how to generate OpenCover report in xml ( https://habr.com/ru/post/163895/ )
4. Make bat-file that will generate report using OpenCover
5. Commit xml-report to this repository
6. Configure GitHub Actions to send code coverage reports to Codacy ( https://github.com/marketplace/actions/codacy-coverage-reporter )

**Comment by Konard** [comment]
Maybe we can use [coverlet.collector](https://github.com/coverlet-coverage/coverlet#usage) that is already connected to all of our repositories.

**Comment by uselessgoddess** [comment]
Lol, C++ has builtin coverage tool

**Comment by Konard** [comment]
We can also try [dotCover](https://www.jetbrains.com/help/dotcover/Running_Coverage_Analysis_from_the_Command_LIne.html)

**Comment by uselessgoddess** [comment]
Lol, proprietary soft

**Comment by aglichandrap** [comment]
## Solution: Enable Test Code Coverage Monitoring

I analyzed the repository and found that the test project (`csharp/Platform.Ranges.Tests/Platform.Ranges.Tests.csproj`) already includes `coverlet.collector` (v3.1.2), which means the coverage infrastructure is partially in place. Here is the complete solution to enable coverage collection and reporting.

### Step 1: Update the CI workflow to collect coverage

Modify `.github/workflows/csharp.yml` to generate a Cobertura coverage report:

```yaml
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Test with coverage
        run: |
          dotnet test -c Release -f net8 \
            --collect:"XPlat Code Coverage" \
            --results-directory ./coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: csharp/coverage/**/coverage.cobertura.xml
```

### Step 2: Add Coveralls integration

Since the repo already has a Coveralls page at https://coveralls.io/github/linksplatform/Ranges, add a coverage upload step after the test job:

```yaml
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Test with coverage
        run: |
          dotnet test -c Release -f net8 \
            --collect:"XPlat Code Coverage" \
            --results-directory ./coverage
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: csharp/coverage/**/coverage.cobertura.xml
          format: cobertura
```

### Step 3: Add Coveralls badge to README

Add this badge near the top of `README.md`, after the existing Codacy badge:

```markdown
[![Coverage Status](https://coveralls.io/repos/github/linksplatform/Ranges/badge.svg?branch=main)](https://coveralls.io/github/linksplatform/Ranges?branch=main)
```

### Why Coveralls over Codacy?

- The repo already has a Coveralls page configured
- `coverlet.collector` generates Cobertura XML, which Coveralls natively supports
- The `coverallsapp/github-action` action is well-maintained and simple to configure
- Codacy can also work but requires a `CODACY_PROJECT_TOKEN` secret, adding setup complexity

### Alternative: Codacy approach

If Codacy coverage is preferred instead, use the `codacy/codacy-coverage-reporter-action`:

```yaml
      - name: Upload to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reporter: csharp/coverage/**/coverage.cobertura.xml
```

### Verification

After implementing, the coverage percentage will appear on the Coveralls badge and the Coveralls dashboard will show per-file coverage details for each commit.

---
*Disclosure: AI agent analysis submitted for issue #36.*

**Comment by aglichandrap** [comment]
## Solution: Enable Test Code Coverage Monitoring

Here's a complete implementation for adding code coverage monitoring using **Coveralls** and **Codacy**, both mentioned in the issue.

### GitHub Actions Workflow

Create `.github/workflows/coverage.yml`:

```yaml
name: Code Coverage

on:
  push:
    branches: [main]
    paths:
      - 'csharp/**'
      - '.github/workflows/coverage.yml'
  pull_request:
    branches: [main]
    paths:
      - 'csharp/**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    working-directory: csharp

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests with coverage
        run: |
          dotnet test Platform.Ranges.Tests/Platform.Ranges.Tests.csproj \
            -c Release \
            --collect:"XPlat Code Coverage" \
            --results-directory ./coverage \
            --logger "trx;LogFileName=test-results.trx"

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: csharp/coverage/*/coverage.cobertura.xml
          format: cobertura

      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: csharp/coverage/*/coverage.cobertura.xml

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: csharp/coverage/
```

### Why This Works

1. **`coverlet.collector` (v3.1.2)** is already a dependency in `Platform.Ranges.Tests.csproj` — no changes needed to the test project
2. `--collect:"XPlat Code Coverage"` generates Cobertura XML reports that both Coveralls and Codacy accept
3. The workflow triggers on changes to `csharp/**` files, matching the existing `csharp.yml` pattern

### Setup Steps

1. **Coveralls**: 
   - Go to [coveralls.io](https://coveralls.io/github/linksplatform/Ranges) and enable the repo
   - `GITHUB_TOKEN` is used automatically — no extra secrets needed

2. **Codacy**:
   - In [Codacy project settings](https://app.codacy.com/manual/drakonard/Ranges/settings/coverage), get the project token
   - Add `CODACY_PROJECT_TOKEN` as a repository secret in GitHub Settings → Secrets → Actions

3. **Add coverage badge** to `README.md`:
   ```markdown
   [![Coverage Status](https://coveralls.io/repos/github/linksplatform/Ranges/badge.svg?branch=main)](https://coveralls.io/github/linksplatform/Ranges?branch=main)
   ```

### Notes

- The `dotnet test` target framework (`net8`) is handled by the test project's `<TargetFramework>net8</TargetFramework>` setting
- Coverage artifacts are uploaded for debugging even if other steps fail (`if: always()`)
- The `coverallsapp/github-action@v2` action handles Cobertura XML format natively

I'm happy to submit this as a PR if the workflow scope is available on the repository token, or a maintainer can apply this file directly.

---
*Disclosure: This comment is in response to the bounty described in this issue.*
